export const FILM_LIST_ACTION_TYPE = {

    FETCH_ALL_FILM_LIST_SUCCESS : 'allFilm/FETCH_FILM_LIST_SUCCESS',
    
    FETCH_TV_FILM_LIST_SUCCESS : 'tvFilm/FETCH_FILM_LIST_SUCCESS',

    FETCH_MOVIE_FILM_LIST_SUCCESS : 'movieFilm/FETCH_FILM_LIST_SUCCESS',

    FETCH_FILM_LIST_START : 'film/FETCH_FILM_LIST_START',
    FETCH_FILM_LIST_FAILED : 'film/FETCH_FILM_LIST_FAILED',
    
}