const FILM_ACTION_TYPES ={
    SET_LIKE_OF_FILM : 'fiml/FILM_SET_LIKE',
    SET_ADD_FILM_TO_WATCHLIST : 'fiml/FILM_EDIT_LIKE',
    SET_OPEN_INFO_BOX: 'fiml/FILM_OPEN_INFO_BOX',
    SET_FILM_FAILED: 'film/FILM_SET_FILM_FAILED',
    CREATE_LIST_FILM : 'film/FILM_CREATE_LIST_FILM'

}
export default FILM_ACTION_TYPES